name: Glance
options:
  bundleIdPrefix: com.julianbaumann
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    SWIFT_STRICT_CONCURRENCY: minimal

targets:
  Glance:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Glance
        createIntermediateGroups: true
    info:
      path: Glance/Info.plist
      properties:
        CFBundleDisplayName: Glance
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UILaunchScreen:
          UIImageName: ""
        NSFaceIDUsageDescription: "Use Face ID to lock Glance and protect your health data."
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.julianbaumann.glance
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        SWIFT_EMIT_LOC_STRINGS: "YES"
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"

  GlanceTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: GlanceTests
    resources:
      - path: Glance/Resources/MarkerData.json
    dependencies:
      - target: Glance
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.julianbaumann.glance.tests
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
        GENERATE_INFOPLIST_FILE: "YES"

  GlanceUITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: GlanceUITests
    dependencies:
      - target: Glance
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.julianbaumann.glance.uitests
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
        GENERATE_INFOPLIST_FILE: "YES"
